# Generated by Django 3.2.9 on 2021-11-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captime', models.DateTimeField()),
                ('accx', models.CharField(max_length=10)),
                ('accy', models.CharField(max_length=10)),
                ('accz', models.CharField(max_length=10)),
                ('magx', models.CharField(max_length=10)),
                ('magy', models.CharField(max_length=10)),
                ('magz', models.CharField(max_length=10)),
                ('gyrx', models.CharField(max_length=10)),
                ('gyry', models.CharField(max_length=10)),
                ('gyrz', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=10)),
            ],
        ),
    ]
